<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Naiad" />
    <PackageReference Include="Naiad.ImageSharp" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
  </ItemGroup>
</Project>
