<Project>
  <ItemGroup>
    <PackageVersion Include="CliFx" Version="3.0.1" />
    <PackageVersion Include="LocalDb" Version="27.2.4" />
    <PackageVersion Include="MarkdownSnippets.MsBuild" Version="28.5.0" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="7.1.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="Microsoft.SqlServer.SqlManagementObjects" Version="181.37.1" />
    <PackageVersion Include="Microsoft.SqlServer.TransactSql.ScriptDom" Version="180.117.0" />
    <PackageVersion Include="Naiad" Version="1.5.2" />
    <PackageVersion Include="Naiad.ImageSharp" Version="1.5.2" />
    <PackageVersion Include="ProjectDefaults" Version="1.0.184" />
    <PackageVersion Include="TUnit" Version="1.73.19" />
    <PackageVersion Include="Verify.TUnit" Version="33.3.2" />
  </ItemGroup>
</Project>